### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by Sdillon215** [Mheyn95/trivia-game#6]
fetch trivia API using user inputs from start modal
fetch GIF api
randomize questions
add correct and incorrect answers to array and randomize them
create answer buttons
display question
check answer

**Comment by Mheyn95** [comment]
This is done. We will need to decide how to track the scores before we can close it though. Right now I have alerts that tell us what is going on that we will also want to replace with modals. We will also need to decide how to handle the displaying of gifs, and which ones we want to display (I have two in there now as placeholders).
